### ISSUE TITLE
Unify or contrast with related efforts

### ISSUE THREAD

**Issue by littledan** [gibson042/ecma262-proposal-uniform-interchange-date-parsing#1]
- @apaprocki has been looking into unifying some cases for Date.parse
- There is a [previous proposal](https://github.com/tc39-transfer/proposal-date-time-string-format) by @mrrrgn about this topic

We have an occasional call to discuss Date-related proposals. Would you like to join?

**Comment by gibson042** [comment]
Yes, I'd love to join the call. I'd welcome input from @apaprocki, and will see what I can harvest from https://github.com/tc39/proposal-date-time-string-format . Thanks.

**Comment by littledan** [comment]
@gibson042 Do you have an email address that would be good for a Google Calendar invite?

**Comment by gibson042** [comment]
Yes, see https://github.com/gibson042/ecma262-proposal-uniform-interchange-date-parsing/commit/4aa69ff06b40492b1fb54fa26ba68aca21660d5d.patch .
