### ISSUE TITLE
Is the intent to still allow implementation-defined fallbacks?

### ISSUE THREAD

**Issue by domenic** [gibson042/ecma262-proposal-uniform-interchange-date-parsing#3]
I'm a bit confused by the ultimate goal of this proposal. Is it meant to expand the well-defined subset, but still allow implementation-defined fallbacks for other cases (e.g. `"1 Octopus 2018"`)?

If so, that would be good to state explicitly and early.

**Comment by gibson042** [comment]
Yes, it is meant to expand the subset of input with well-defined behavior (primarily to include standardized _rejection_ of out-of-bounds or otherwise slightly invalid data, and secondarily to accept a broader subset of valid ISO 8601 calendar date-time values). Clarifying update forthcoming.
